version: '3'

services:
  website:
    build: .
    container_name: berkay-inam-website
    ports:
      - "9999:9999"
    restart: unless-stopped
    networks:
      - website-network

networks:
  website-network:
    driver: bridge 